### ISSUE TITLE
Make it run in a docker container with PHP 7.1!

### ISSUE THREAD

**Issue by andrerademacher** [andrerademacher/zce71#2]
At the moment, to run the tests you need to have installed PHP 7.1 on your machine. Most likely, parallel to your _real_ PHP version. Here, it would be much nicer to be able to run the tests inside a docker container, without any arcane knowledge.

Currently:
$ ./t71.sh <additional optional parameters>
... phpunit stuff ...

Then:

$ ./t71withDocker.sh <additional optional parameters>
... docker stuff ...
... phpunit stuff ...

ToDo:
- [ ] Add a shell script that runs the tests inside a docker container.
- [ ] This should maybe check if docker is installed, and if not, give a hint to the docker install URL

**Comment by carlosgomezmx** [comment]
Here is my pull request https://github.com/andrerademacher/zce71/pull/3

**Comment by andrerademacher** [comment]
Awesome, thx! Wish u a happy Hacktoberfest.
